### ISSUE TITLE
Only works in discord.py 1.7.x

### ISSUE THREAD

**Issue by BadUserHater** [SonicTheDev/RoleplayBot.py#1]
This code seems to only work in discord.py 1.7.x

That means you would have to include in the readme that Discord.py 1.7.x is required. You should make a requirements file that does: discord.py==1.7.1
Either that or find another way to use webhooks in discord.py 2.0

**Comment by SonicTheDev** [comment]
Thank you for telling me about this issue. I will add the file.

**Comment by SonicTheDev** [comment]
Code has been updated as well as the requirements file so the code can now be used with discord.py 2.0
